### PR TITLE
Finishing Episode 1 support

### PR DESCRIPTION
**Pull request by knoxed**
# Finishing EP1 gametype support

This is a work in progress. Opened PR so we can have a list of all the stuff that has to be added or bugs to be fixed.

Up to map script **ep1_c17_00** everything _should_ be finished already.

## General TODO

- [x] Figure out crashing on map ep1_c17_00a (and even 00) (something with antlions maybe?)
- [x] Check and make sure episodic content is mounted and loaded correctly.
> Intro in ep1_citadel_00 still has some missing content (blue vorts and missing animations)
- [x] Add medkit to default loadout on every map.
- [x] Change the doors at the end of _00 to be always open.

## ep1_c17_00a
- [x] Checkpoints.
- [x] Add wait trigger to the elevator which then goes up to changelevel trigger.
- [x] Fix the door closing too soon in horde area and also adding a checkpoint BEFORE elevator

## ep1_c17_01
- [x] Checkpoints.
- [x] Prevent combine wall closing

## ep1_c17_02
- [x] Checkpoints.
- [ ] ~~Add a teamwait keyvalue to the elevator in the vent maze at the end~~ <- I rather would not!

## ep1_c17_02a
- [x] Checkpoints.
- [ ] Fix alyx not picking up a shotgun when she should.

## ep1_c17_02b
- [x] Checkpoints

## ep1_c17_05
- [x] Checkpoints
- [x] Make NPCs follow you along with a billion other issues that appeared. Mostly works ATM

## ep1_c17_06
- [x] Checkpoints
- [x] Wait trigger for all to hop on the train

__*__ - _Has yet to be play tested with multiple people to see what map logic has to be modified._

Feel free to play test this branch and leave feedback.

### CODE REVIEW

**Comment by ZhylevarYTRUS** [comment]
"CSceneEntity alyx :"Alyx" failed to start sequence "alyx_wall_lean""

**Review by ZhylevarYTRUS — COMMENTED** [review]
"CSceneEntity alyx :"Alyx" failed to start sequence "alyx_wall_lean""
Can you guys fix that error?
Also, alyx is muted, she doesn't say something.

**Comment by ZehMatt** [comment]
> "CSceneEntity alyx :"Alyx" failed to start sequence "alyx_wall_lean"" Can you guys fix that error? Also, alyx is muted, she doesn't say something.

In which map is this? Also make sure that no other addons are conflicting with Lambda, try to disable all of them except Lambda.

**Comment by ZhylevarYTRUS** [comment]
https://github.com/GMLambda/Lambda/pull/258#issuecomment-2002034900
on ep_c17_00 on start. Also i dont have any addons except Lambda and Half - Life 2 & Ep1 Maps.

**Comment by ZehMatt** [comment]
> [#258 (comment)](https://github.com/GMLambda/Lambda/pull/258#issuecomment-2002034900) on ep_c17_00 on start. Also i dont have any addons except Lambda and Half - Life 2 & Ep1 Maps.

I can't reproduce this, we do have some custom models that merged the animations/sequences of episodic models, it might be just that you started playing Sandbox or any other game mode first which loads the default models which prevents from loading the custom ones afterwards.

**Comment by ZhylevarYTRUS** [comment]
> > [#258 (комментарий)](https://github.com/GMLambda/Lambda/pull/258#issuecomment-2002034900) к ep_c17_00 в начале. Также у меня нет никаких аддонов, кроме карт Lambda и Half-Life 2 и Ep1.
> 
> Я не могу это воспроизвести, у нас есть несколько пользовательских моделей, в которых объединены анимации/последовательности эпизодических моделей. Возможно, вы просто сначала начали играть в «Песочницу» или любой другой игровой режим, который загружает модели по умолчанию, что предотвращает загрузку пользовательских. после.

no, its still don't work.

**Review by ZehMatt — APPROVED** [review]

**Pull request merged**
