### PR TITLE
Improve some section of d1_canals_05

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Review by dounai2333 — COMMENTED** [review]
Do we really need this? This area seems will not cause any issue.
Unless some servers has "[Walk on Moving Props!](https://steamcommunity.com/sharedfiles/filedetails/?id=2512464000)" installed or "sv_gravity 800".
Even so, player can always destroy every wooden boards and continue complete the map.

**Comment by ZehMatt** [comment]
> Do we really need this? This area seems will not cause any issue. Unless some servers has "[Walk on Moving Props!](https://steamcommunity.com/sharedfiles/filedetails/?id=2512464000)" installed or "sv_gravity 800". Even so, player can always destroy every wooden boards and continue complete the map.

I died serval times on this section due to physics glitching out here

https://github.com/GMLambda/Lambda/assets/5415177/91b16317-0d8e-48e6-8861-88e069faea6f

**Comment by dounai2333** [comment]
> I died serval times on this section due to physics glitching out here

I have tried to reproduce same thing in video, hard to say that if it's not intentional.
Tried do workaround by 10 bots + me, with no collision, doing several times of "only walking", "walking with several jumps" and "bunnyhopping", I do see 2 or 3 bots dying by the physics bug, in a large server with many rushing players it indeed is a problem we need to take attention since they don't want to die with no reason.

How about we give "FVPHYSICS_NO_IMPACT_DMG" flag to the physics object? This solve the issue more smart and player will not notice.

**Comment by ZehMatt** [comment]
> > I died serval times on this section due to physics glitching out here
> 
> I have tried to reproduce same thing in video, hard to say that if it's not intentional. Tried do workaround by 10 bots + me, with no collision, doing several times of "only walking", "walking with several jumps" and "bunnyhopping", I do see 2 or 3 bots dying by the physics bug, in a large server with many rushing players it indeed is a problem we need to take attention since they don't want to die with no reason.
> 
> How about we give "FVPHYSICS_NO_IMPACT_DMG" flag to the physics object? This solve the issue more smart and player will not notice.

Its not the physics object that damages the player this rather causes the movement of the player to freak out and puts the player in a falling limbo. I think just freezing the objects is the best workaround, maybe also prevent them from breaking perhaps. It's a small section anyway and I don't want players to die to random shit like that.

**Comment by dounai2333** [comment]
> Its not the physics object that damages the player this rather causes the movement of the player to freak out and puts the player in a falling limbo. I think just freezing the objects is the best workaround, maybe also prevent them from breaking perhaps. It's a small section anyway and I don't want players to die to random shit like that.

The video you posted is **very hard** to reproduce if player is ***not doing it intentional***.
With test with bots, I got more issues from physics object impact rather than the issue that video shown.

**Comment by ZehMatt** [comment]
> > Its not the physics object that damages the player this rather causes the movement of the player to freak out and puts the player in a falling limbo. I think just freezing the objects is the best workaround, maybe also prevent them from breaking perhaps. It's a small section anyway and I don't want players to die to random shit like that.
> 
> The video you posted is **very hard** to reproduce if player is _**not doing it intentional**_. With test with bots, I got more issues from physics object impact rather than the issue that video shown. 

Well freezing them would also solve this, also I died a couple of times there without trying to really die 😄 It happens often enough as that is one of the first places where the player can go down.

**Review by dounai2333 — APPROVED** [review]

**Pull request merged**
